absl-py==2.0.0
aiobotocore==2.11.2
aiohttp==3.9.1
aioitertools==0.11.0
aiosignal==1.3.1
alabaster==0.7.13
anndata==0.9.2
annotated-types==0.6.0
antlr4-python3-runtime==4.9.3
anyio==4.1.0
appdirs==1.4.4
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
arrow==1.3.0
asciitree==0.3.3
asttokens==2.4.1
astunparse==1.6.3
async-lru==2.0.4
async-timeout==4.0.3
attrs==23.1.0
Babel==2.13.1
backcall==0.2.0
beautifulsoup4==4.12.2
bleach==6.1.0
botocore==1.34.34
cached-property==1.5.2
cachetools==5.3.2
catenets==0.2.3
cellxgene_census==1.10.0
certifi==2023.11.17
cffi==1.16.0
charset-normalizer==3.3.2
chex==0.1.7
ChromaPalette==0.1.1
click==8.1.7
cloudpickle==3.0.0
comm==0.2.0
ConfigArgParse==1.7
configparser==6.0.0
contextlib2==21.6.0
contourpy==1.1.1
cycler==0.12.1
dask==2023.5.0
dask-image==2023.3.0
debugpy==1.8.0
decorator==5.1.1
deepimpute==1.2
defusedxml==0.7.1
Deprecated==1.2.14
dm-tree==0.1.8
docker-pycreds==0.4.0
docrep==0.3.2
docutils==0.20.1
einops==0.7.0
et-xmlfile==1.1.0
etils==1.3.0
exceptiongroup==1.2.0
executing==2.0.1
fasteners==0.19
fastjsonschema==2.19.0
filelock==3.13.1
flatbuffers==23.5.26
flax==0.7.2
fonttools==4.46.0
fqdn==1.5.1
frozenlist==1.4.0
fsspec==2024.2.0
future==0.18.3
gast==0.4.0
gcastle==1.0.4rc1
gdown==4.7.1
get-annotations==0.1.2
gitdb==4.0.11
GitPython==3.1.41
google-auth==2.27.0
google-auth-oauthlib==1.0.0
google-pasta==0.2.0
graphtools==1.5.3
grpcio==1.59.3
h5py==3.10.0
harmonypy==0.0.9
idna==3.6
igraph==0.10.8
imageio==2.33.1
imagesize==1.4.1
importlib-metadata==6.9.0
importlib-resources==6.1.1
inflect==7.0.0
iniconfig==2.0.0
ipykernel==6.27.1
ipython==8.12.3
ipywidgets==8.1.1
isoduration==20.11.0
jax==0.4.13
jaxlib==0.4.13
jedi==0.19.1
Jinja2==3.1.2
jmespath==1.0.1
joblib==1.3.2
json5==0.9.14
jsonpointer==2.4
jsonschema==4.20.0
jsonschema-specifications==2023.11.2
jupyter==1.0.0
jupyter_client==8.6.0
jupyter-console==6.6.3
jupyter_core==5.5.0
jupyter-events==0.9.0
jupyter-lsp==2.2.1
jupyter_server==2.11.1
jupyter_server_terminals==0.4.4
jupyterlab==4.0.9
jupyterlab_pygments==0.3.0
jupyterlab_server==2.25.2
jupyterlab-widgets==3.0.9
keras==2.13.1
kiwisolver==1.4.5
laboratory==1.0.2
lazy_loader==0.3
legendkit==0.3.4
leidenalg==0.10.1
libclang==16.0.6
lightning-utilities==0.10.0
llvmlite==0.41.1
locket==1.0.0
loguru==0.7.2
magic-impute==3.0.0
Markdown==3.5.1
markdown-it-py==3.0.0
MarkupSafe==2.1.3
marsilea==0.4.1
matplotlib==3.7.5
matplotlib-inline==0.1.6
matplotlib-scalebar==0.8.1
mdurl==0.1.2
mistune==3.0.2
ml-collections==0.1.1
ml-dtypes==0.2.0
mnnpy==0.1.9.5
mpmath==1.3.0
msgpack==1.0.7
mudata==0.2.3
multidict==6.0.4
multipledispatch==1.0.0
munch==4.0.0
natsort==8.4.0
nbclient==0.9.0
nbconvert==7.11.0
nbformat==5.9.2
nbsphinx==0.9.3
nest-asyncio==1.5.8
networkx==3.1
notebook==7.0.6
notebook_shim==0.2.3
numba==0.58.1
numcodecs==0.12.1
numpy==1.22.4
numpyro==0.12.1
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.18.1
nvidia-nvjitlink-cu12==12.3.101
nvidia-nvtx-cu12==12.1.105
oauthlib==3.2.2
omegaconf==2.3.0
omnipath==1.0.8
openpyxl==3.1.2
opt-einsum==3.3.0
optax==0.1.7
orbax-checkpoint==0.2.3
overrides==7.4.0
packaging==23.2
pandas==1.5.3
pandocfilters==1.5.0
parso==0.8.3
partd==1.4.1
patsy==0.5.4
pertvi==0.0.1
pexpect==4.9.0
pickleshare==0.7.5
Pillow==10.1.0
PIMS==0.6.1
pip==23.3.1
pkgutil_resolve_name==1.3.10
platformdirs==4.0.0
plottable==0.1.5
pluggy==1.5.0
prettytable==3.9.0
prometheus-client==0.19.0
prompt-toolkit==3.0.41
protobuf==4.25.1
psutil==5.9.6
ptyprocess==0.7.0
pure-eval==0.2.2
pyarrow==14.0.2
pyarrow-hotfix==0.6
pyasn1==0.5.1
pyasn1-modules==0.3.0
pycparser==2.21
pydantic==2.5.3
pydantic_core==2.14.6
pyDeprecate==0.3.1
pydot==1.4.2
Pygments==2.17.2
PyGSP==0.5.1
pynndescent==0.5.11
pyparsing==3.1.1
pyro-api==0.1.2
pyro-ppl==1.8.6
PySocks==1.7.1
pytest==8.2.1
python-dateutil==2.8.2
python-json-logger==2.0.7
pytorch-lightning==1.5.10
pytz==2023.3.post1
PyWavelets==1.4.1
PyYAML==6.0.1
pyzmq==25.1.1
qtconsole==5.5.1
QtPy==2.4.1
ray==2.9.0
referencing==0.31.1
requests==2.31.0
requests-oauthlib==1.3.1
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rich==13.7.0
rpds-py==0.13.2
rsa==4.9
ruamel.yaml==0.18.5
ruamel.yaml.clib==0.2.8
s3fs==2024.2.0
scanpy==1.9.6
scib==1.1.4
scib-metrics==0.3.3
scikit-image==0.21.0
scikit-learn==1.3.2
scikit-misc==0.2.0
scipy==1.10.1
sconf==0.2.5
scprep==1.2.3
scvi-tools==0.16.2
seaborn==0.12.2
Send2Trash==1.8.2
sentry-sdk==1.39.2
session-info==1.0.0
setproctitle==1.3.3
setuptools==59.5.0
six==1.16.0
slicerator==1.1.0
smmap==5.0.1
sniffio==1.3.0
snowballstemmer==2.2.0
somacore==1.0.7
soupsieve==2.5
Sphinx==7.1.2
sphinxcontrib-applehelp==1.0.4
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.1
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
squidpy==1.2.3
stack-data==0.6.3
statsmodels==0.14.0
stdlib-list==0.10.0
sympy==1.12
tasklogger==1.2.0
tensorboard==2.13.0
tensorboard-data-server==0.7.2
tensorboard-plugin-wit==1.8.1
tensorboardX==2.6.2.2
tensorflow==2.13.1
tensorflow-estimator==2.13.0
tensorflow-io-gcs-filesystem==0.34.0
tensorstore==0.1.45
termcolor==2.4.0
terminado==0.18.0
texttable==1.7.0
threadpoolctl==3.2.0
tifffile==2023.7.10
tiledb==0.25.0
tiledbsoma==1.7.0
tinycss2==1.2.1
tomli==2.0.1
toolz==0.12.0
torch==2.1.1
torch_geometric==2.5.3
torchmetrics==1.2.1
torchvision==0.16.1
tornado==6.4
tqdm==4.66.1
traitlets==5.14.0
triton==2.1.0
types-python-dateutil==2.8.19.14
typing_extensions==4.8.0
tzdata==2023.3
umap-learn==0.5.5
uri-template==1.3.0
urllib3==1.26.18
validators==0.22.0
vedo==2024.5.1
vtk==9.3.0
wandb==0.16.2
wcwidth==0.2.12
webcolors==1.13
webencodings==0.5.1
websocket-client==1.7.0
Werkzeug==3.0.1
wheel==0.41.2
widgetsnbextension==4.0.9
wrapt==1.16.0
xarray==2023.1.0
yarl==1.9.3
zarr==2.16.1